###User-Customer
################################
##Get all user
POSt http://localhost:5000/api/user/getusers

################################
##register
POSt http://localhost:5000/api/user/register
Content-Type: application/json

{
    "fullName":"3prevlife3",
    "phone":"4",
    "password":"1234"
}

################################
##check user
POST http://localhost:5000/api/user/
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwaG9uZSI6IjIiLCJpYXQiOjE2NDA0MzAyNzF9.bWBwAkbjPW8X1nzNIUp-IJUGA4bY3J-hqmzE6Xii7SA


################################
##login
POSt http://localhost:5000/api/user/login
Content-Type: application/json

{
    "phone":"2",
    "password":"1234"
}


###Staff
################################
##Get all staff
POSt http://localhost:5000/api/staff/getUsers

################################
##register
POSt http://localhost:5000/api/staff/register
Content-Type: application/json

{
    "fullName":"prevlife",
    "phone":"1",
    "password":"1234",
    "role":""
}
################################
##login
POSt http://localhost:5000/api/staff/login
Content-Type: application/json

{
    "phone":"4",
    "password":"1234"
}



################################
################################
##Products
GET http://localhost:5000/api/product/getproducts
################################
##Create new product
POSt http://localhost:5000/api/product/create
Content-Type: application/json

{
    "nameProduct":"first product",
    "priceProduct":"",
    "imageProduct":"first url image product",
    "description":{
        "brand":"first brand",
        "category":"first category",
        "cpu":"first cpu",
        "ram":"first ram",
        "battery":"first battery"
    }
}

################################
##Update post
POST http://localhost:5000/api/product/update/61c048a16415aa87740c684e
Content-Type: application/json

{
    "nameProduct":"second product",
    "priceProduct":1511,
    "description":{
        "ram":"prevRAM"
    }
}

################################
##find product by ID
Get http://localhost:5000/api/product/find/61c048a16415aa87740c684e

################################
##delete product
POST http://localhost:5000/api/product/delete/61c0524f8ed92b2dd5b2429d

################################
##getall favourite
GET http://localhost:5000/api/favourite/getfavourites
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwaG9uZSI6IjQiLCJpYXQiOjE2NDAwNTE3MTB9.t6W4KoRjGLSntNt2HutpRrvtDTIp0K97NOwiWFxL31M


################################
##get favourite by userId -> is phonenumber
GET http://localhost:5000/api/favourite/
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwaG9uZSI6IjEiLCJpYXQiOjE2NDAwNTIxMDR9.dy7G847_qxnvzQCTtTV4Cvz-3SRUUY79_B7IGUHNT_w


################################
##post add favourite
post http://localhost:5000/api/favourite/add
Content-Type: application/json

{
    "userId":"2",
    "productFavourite":"11"
}

###############################
##post remove favourite
post http://localhost:5000/api/favourite/remove
Content-Type: application/json

{
    "userId":"2",
    "productFavourite":"1"
}


################################

##getall cart
GET http://localhost:5000/api/cart/getcarts
################################
##get cart by userId -> is phonenumber
GET http://localhost:5000/api/cart/
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwaG9uZSI6IjIiLCJpYXQiOjE2NDAwNTMzNTN9.gs8mnMtTTiaoNEVGc8gUHmDt1NzDJLxvCLVkpXxWHOs


################################
##post add product to cart
post http://localhost:5000/api/cart/add
Content-Type: application/json

{
    "userId":"1",
    "productCart":"1",
    "countProductCart": 4
}

################################
##post remove product from cart
post http://localhost:5000/api/cart/remove
Content-Type: application/json

{
    "userId":"2",
    "productCart":"1"
}
################################
##post clear cart by userId
POST http://localhost:5000/api/cart/clear
Content-Type: application/json

{
    "userId":"2"
}